name: Setup LaTeX
description: Setup LaTeX.

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get -y install --no-install-recommends \
          build-essential ca-certificates tzdata gnupg cpanminus libc6-dev
        sudo apt-get autoremove -y
        sudo apt-get clean autoclean -y
      shell: bash
    - uses: actions/cache@v2
      id: cache-texlive
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('/usr/local/texlive/2021/release-texlive.txt') }}
    - run: |
        mkdir /tmp/texlive
        cd /tmp/texlive
        wget -qO- "http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/install-tl-unx.tar.gz" \
          | tar -xz --strip-components=1
        touch profile.txt
        echo "selected_scheme scheme-basic" >> profile.txt
        echo "instopt_letter 0" >> profile.txt
        echo "tlpdbopt_autobackup 0" >> profile.txt
        echo "tlpdbopt_desktop_integration 0" >> profile.txt
        echo "tlpdbopt_file_assocs 0" >> profile.txt
        echo "tlpdbopt_install_docfiles 0" >> profile.txt
        echo "tlpdbopt_install_srcfiles 0" >> profile.txt
        sudo perl install-tl -profile profile.txt \
          --location "http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet"
        rm -r /tmp/texlive
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      shell: bash
    - run: |
        sudo cpanm -n -q Log::Log4perl
        sudo cpanm -n -q XString
        sudo cpanm -n -q Log::Dispatch::File
        sudo cpanm -n -q YAML::Tiny
        sudo cpanm -n -q File::HomeDir
        sudo cpanm -n -q Unicode::GCString
      shell: bash
    - run: |
        sudo echo 'PATH="/usr/local/texlive/2021/bin/$(uname -m)-linux:$PATH"' >> /root/.profile
        sudo tlmgr update --self --all --reinstall-forcibly-removed
        sudo tlmgr install \
          chktex comment enumitem latexindent latexmk lastpage revtex textcase ulem xcolor
        sudo texhash
      shell: bash
