name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-texlive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: pip
      - run: |
          pip3 install invoke==1.6.0
          invoke lint
