name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup TexLive
        uses: ./.github/actions/setup-texlive
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - name: Lint
        run: |
          invoke lint
