name: Workflow - On Tags

on:
  push:
    tags:        
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup TexLive
        uses: ./.github/actions/setup-texlive
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - name: Build
        run: |
          invoke build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/*.pdf

  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - name: Release
        run: |
          invoke release
      - name: Get Version From Tag
        run: |
          version=`echo $GITHUB_REF | cut -d/ -f3`
          echo "::set-output name=version::$version"
      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.version }}
          fail_on_unmatched_files: true
          files: dist/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
