name: Workflow - On Tags

on:
  push:
    tags:        
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-texlive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip3 install invoke==1.6.0
      - run: |
          invoke build

  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-texlive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip3 install invoke==1.6.0
      - run: |
          invoke release
      - run: |
          echo "::set-output name=version::${GITHUB_REF#refs/*/}"
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.version }}
          files: dist/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
